AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: webapp

Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
  AcmCertificateArn:
    Description: AcmCertificateArn
    Type: String
  HostedZoneId:
    Description: HostedZoneId
    Type: String
Resources:
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref RootDomainName, '/*']]
            Principal: "*"
  WebAppCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref RootDomainName
  WebAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [WebAppBucket, DomainName]
            Id: !Join ['', ['S3-', !Ref RootDomainName]]
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref WebAppCloudFrontOriginAccessIdentity]]
        Enabled: 'true'
        Comment: Some comment
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases:
          - !Ref RootDomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: !Join ['', ['S3-', !Ref RootDomainName]]
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - VN
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
  WebAppDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: Zone apex alias.
      RecordSets:
        -
          Name: !Ref RootDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [WebAppDistribution, DomainName]
Outputs:
  WebsiteURL:
    Value: !Ref RootDomainName
    Description: URL for website hosted on S3
  DistributionID:
    Value: !Ref WebAppDistribution
    Description: Distribution ID
